### ISSUE TITLE
Unable to install liquidsoap due to libmad and libmp3lame dependency issues

### ISSUE THREAD

**Issue by amavarick** [radiorabe/centos-rpm-liquidsoap#1]
Using CentOS 7 64 bit
CentOS Linux release 7.2.1511 (Core)
2.6.32-042stab113.17 #1 SMP Wed Feb 10 18:31:00 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

`[root@stream yum.repos.d]# yum install http://download.opensuse.org/repositories/home:/radiorabe:/liquidsoap/CentOS_7/home:radiorabe:liquidsoap.repo
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
- base: dallas.tx.mirror.xygenhosting.com
- extras: dallas.tx.mirror.xygenhosting.com
- rpmforge: mirror.team-cymru.org
- updates: centos.mirror.lstn.net
  No package http://download.opensuse.org/repositories/home:/radiorabe:/liquidsoap/CentOS_7/home:radiorabe:liquidsoap.repo available.
  Error: Nothing to do`

I then:
``cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/home:radiorabe:liquidsoap/CentOS_7/home:radiorabe:liquidsoap.repo
yum update
yum install liquidsoap`

Which resulted in the following response:
`--> Finished Dependency Resolution
Error: Package: liquidsoap-1.2.1-14.3.x86_64 (home_radiorabe_liquidsoap)
           Requires: libmad.so.0()(64bit)
Error: Package: liquidsoap-1.2.1-14.3.x86_64 (home_radiorabe_liquidsoap)
           Requires: libmp3lame.so.0()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
``

Could you help me resolve this issue?  I'd like to keep to repos to allow these packages to update rather than manually installing.  If it does require manual install, could you identify the recommended locations of the dependency packages?

Thank you so much for your time...

**Comment by hairmare** [comment]
Hi @amavarick 

You seem to be missing `libmad` and `lame` which are both available from the [nux dextop repo](http://li.nux.ro/repos.html). 

Thanks for the feedback. I'll close the issue after adding a `Require` and updating the docs.

**Comment by hairmare** [comment]
`liquidsoap-1.2.1-16.1` expressing the `lame` and `libmad` requirement was just built and published on obs and I also updated the readme.

I'm closing this since it should be fixed. Please let me know if you encounter any further issues.

**Comment by amavarick** [comment]
Lucas,
Thank you SOOO much for your contribution.  Your new instructions worked.  I generally don't like to compile and install manually when a repo is available because it would complicate upgrade process for me later.

Date: Tue, 9 Aug 2016 01:33:48 -0700
