### ISSUE TITLE
Liquidsoap 1.3.3

### ISSUE THREAD

**Issue by amavarick** [radiorabe/centos-rpm-liquidsoap#14]
Would you consider upgrading repo to Liquidsoap 1.3.3?  There's a new time function that is going to be super useful.  Thank you again for such a great contribution.

**Comment by hairmare** [comment]
I plan on doing the update but want to do some serious testing beforehand. The main reason for the delay is that liquidsoap officially dropped support for the version of the Ocaml compiler bundled with CentOS.
I want to take some time to figure out if everything still works as updating Ocaml doesn't really seem to be a sensible way forward.
