### ISSUE TITLE
jackd and icecast

### ISSUE THREAD

**Issue by jeremiel26** [radiorabe/centos-rpm-liquidsoap#17]
Hi,
it would be cool to use your packages to install liquidsoap on my CentOS but i need support for jackd and stream to icecast server.
That's why i actually install it using OPAM cmd:

`opam install taglib lame vorbis lastfm ogg cry samplerate bjack flac theora gavl samplerate taglib magic xmlplaylist soundtouch camomile alsa ao ladspa xmlm camlimages inotify opus liquidsoap`

Do you think it could be possible to add these compilations options to your spec file?

Thx!

**Comment by hairmare** [comment]
Jack support seems doable. Streaming to icecast2 should already work.

Getting ocaml-bjack built was easy and I'm waiting for the dep to get published on the build service. As of lately this usually takes a while.

I'll do a PR to support jack a soon as I get my hands on the package.

**Comment by hairmare** [comment]
packages with jackd support through ocaml-bjack just built on OBS.
