### ISSUE TITLE
Liquidsoap 1.3.4

### ISSUE THREAD

**Issue by edinsof** [radiorabe/centos-rpm-liquidsoap#20]
Hi you planning to update to this liquidsoap version ?

**Comment by hairmare** [comment]
Yes, absolutely. Thanks for creating this issue, this is now the 1.3.4 tracker issue.

I've been trying to clean up some dependencies like pcre-ocaml that I want to add to the 1.3.4 bump and have run into some issues (I'll need to fork the pcre-ocaml spec and figure out why it doesn't build).

I'm hoping it wont take as long as the 1.3.3 bump but I'm not assuming that I'll get it done before Q1 2019.

**Comment by hairmare** [comment]
Some of the changes you are after might have already landed in the latest rebuild of the 1.3.3 packages due to an `ocaml-duppy` package bump.
Nevertheless everything looks good fo far so and we can most likely do the bump to 1.3.4 much earlier than I initially promised 😃

**Comment by edinsof** [comment]
thank you =)
