### ISSUE TITLE
Unable to update to 1.3.7

### ISSUE THREAD

**Issue by TheRealMattLear** [radiorabe/centos-rpm-liquidsoap#28]
I can see the spec file has been bumped to 1.3.7 however running the standard installation procedure results in liquidsoap-1.3.6-80.4.x86_64 being installed.

**Comment by hairmare** [comment]
I had to manually trigger a build, the package should be available soon.

**Comment by hairmare** [comment]
Closing as fixed since the package should now be available. Let me know if you encounter any issues with the package.
