### ISSUE TITLE
variable mksafe not previously defined

### ISSUE THREAD

**Issue by amavarick** [radiorabe/centos-rpm-liquidsoap#3]
I used the following liq file:

```
#!/usr/bin/liquidsoap
# load a playlist file
stream = playlist("/home/music")
# output the playlist to icecast
source = output.icecast(%mp3, host="localhost", port=8000,
         mount="listen.m3u", password="mypassword")
mksafe(source(stream))
```

Then ran the check against the liq file:

`liquidsoap --check ./radio.liq`

and received the following output:

`At line 9, char 7: the variable mksafe used here has not been previously
  defined.`

Doing research it appears as though this link may provide some assistance:
https://sourceforge.net/p/savonet/mailman/savonet-users/thread/5087204C.6030409@queret.net/

Here are some comments from the link:
It is a function defined in utils.liq.

> Make sure you include pervasives.liq, which will automatically include
> utils.liq and all other necessary files.

**Comment by hairmare** [comment]
It looks like liquidsoap is looking for the liq files in the wrong directory.

```
  --no-pervasives 
      Do not load pervasives script libraries (i.e.,
      /usr/local/lib/liquidsoap/1.2.1/*.liq).
```

Somehow it still assumes to be a local build and checks below `/usr/local`. I think parts of this are derived from the actual binary location.

That the package does not install below `/usr` is something I'll change in the next build. I'll have to look into getting rid of the `local` part.

**Comment by hairmare** [comment]
I cleaned up the install by moving stuff to `/usr` and making the configure paths match with what was being installed in the end. As of `liquidsoap-1.2.1-24.1` it searches for pervasives in `/usr/lib/liquidsoap/1.2.1/*.liq` where they are also installed.

Thanks for testing and reporting back if you have any more issues.

**Comment by makew0rld** [comment]
For anyone else who comes across this, here is what I did after installing liquidsoap through the Debian package repositories.

```
sudo mkdir /usr/share/liquidsoap/1.4.1
sudo ln -s /usr/share/liquidsoap/libs /usr/share/liquidsoap/1.4.1/
```
After this, `mksafe` worked, because liquidsoap looks for it in `/usr/share/liquidsoap/<VERSION>/libs`. Make sure to change `1.4.1` to your current version of liquidsoap.
