### ISSUE TITLE
Liquidsoap hanging on shutdown

### ISSUE THREAD

**Issue by AxisNL** [radiorabe/centos-rpm-liquidsoap#30]
Hey, I see you are the maintainer of the RPM packages for liquidsoap in this repo. Thank you for your awesome work, we've been running your RPM's for quite a while now on a few servers.

We're running into a strange issue with liquidsoap 1.3.6 (and I think 1.3.7 as well, but not entirely sure). Sometimes liquidsoap will hang during shutdown. 

I've been pulling my hair out to get this sorted. Unfortunately I cannot reproduce the bug, it just sometimes happens and the most inconvenient times ;)

I made an issue in the liquidsoap repo: https://github.com/savonet/liquidsoap/issues/843

Now I don't know much about compiling my own code, and I'd really like to keep using your RPM's. 

I see two issues there that could cause this issue, at least that's what the people in the topics are talking about. Apparently there was a problem in ocaml-duppy 0.60 that could cause this issue, and it is advised to compile with ocaml-duppy >= 0.80.

The other thing is that there is some instability in ocaml-gstreamer. This seems to be fixed: https://github.com/savonet/ocaml-gstreamer/pull/11 but it looks like this code was not merged into master yet. I asked the maintainer of that project to please look into that. I have no idea if that can take days or months.

Question for you: do you know what version of ocaml-duppy was used to compile your liquidsoap 1.3.6 and 1.3.7 packages for centos7?

And if you have any more ideas to help out, I'd surely love to hear them. 

Kind regards from the Caribbean ;)

**Comment by hairmare** [comment]
The RPMs are built against ocaml-duppy 0.8.0.

I'm also looking forward to rebuilding against a new release on ocaml-gstreamer, although it might take some time to do so after the it is released depending on if we need a newer ocaml version that what is available in CentOS.

Apart from not using gstreamer (I don't use it and I haven't seen you issues) I don't have any ideas on how to fix and/or workaround this.

Let me know if you figure out if any other dependency update can help and I'll bump it and do a rebuild.

**Comment by AxisNL** [comment]
@hairmare , thanks for your reply! Then I know ocaml-duppy is not the issue. I got a reply from @Crocket in the thread https://github.com/savonet/ocaml-gstreamer/issues/12, telling me I should just use the pull request as a patch: https://patch-diff.githubusercontent.com/raw/savonet/ocaml-gstreamer/pull/11.patch.

Would this work?

**Comment by hairmare** [comment]
Let me check if it applies to the latest ocaml-gstrreamer tag and I can tell you. Preferably some input from the savonet team would be nice though.

**Comment by hairmare** [comment]
This is weird, gstreamer can't be your issue, the RPM is built without it. The following section from the configure output show that gst isn't enabled:
```
* Input / output 
- Icecast/Shoutcast : yes 
- AO : no (requires ao) 
- OSS : yes 
- ALSA : yes 
- Portaudio : no (requires portaudio) 
- Pulseaudio : no (requires pulseaudio) 
- JACK : yes 
- GStreamer : no (requires gstreamer)
```
I guess we can rule out gstreamer being the issue :stuck_out_tongue: 

Can you check if the issue still occurs with 1.3.7? There is an 1.3.7 package in the repo so updating should be easy.

**Comment by hairmare** [comment]
I just realized, the old 1.3.6 RPMs have probably never been rebuilt against ocaml-duppy 0.8.0... If you issue is really fixed with the duppy change we can't rule that out unless you can reproduce with the 1.3.7 packages. Building 1.3.6 RPMs with a bumped duppy would in theory be possible but it's well outside of the scope of what we at @radiorabe can support.

**Comment by AxisNL** [comment]
Yeah, we're trying 1.3.7 as we speak. I think we've had the issue again, but have to check to confirm..

to be sure:
$ rpm -qa | grep liq
liquidsoap-1.3.7-82.1.x86_64
$ md5sum /usr/bin/liquidsoap 
4ffe52cc646da0bb208d168835b13927  /usr/bin/liquidsoap
$ liquidsoap --version
Liquidsoap 1.3.7
Copyright (c) 2003-2019 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.

**Comment by TheRealMattLear** [comment]
Our users are also complaining of shutdown issues from this RPM build. We've moved to manually compiled instances via OPAM with OCAML 4.07.1 and this has resolved the problems. We'd lve to switch back over to the RPM builds once this is resolved!

**Comment by hairmare** [comment]
I just pushed liquidsoap 1.4.3 packages for CentOS 8 to the repos 🚀 Can you check if this still reproduces using those packages on CentOS 8?

**Comment by AxisNL** [comment]
Our control panel provider upgraded to 1.4 (compiled via opam), and since then we haven't seen these issues anymore! So thanks everyone!
