### ISSUE TITLE
Liquidsoap 1.4.0

### ISSUE THREAD

**Issue by edinsof** [radiorabe/centos-rpm-liquidsoap#31]
Hi
when update to Liquidsoap 1.4.0 ?

**Comment by hairmare** [comment]
1.4.0 will most likely have to target CentOS 8 due it requiring an updated ocaml.

I'm currently still missing some dependencies to be able to target CentOS 8.

I'll have to check if some of the missing deps are in 8.1 but can't currently give an ETA for 1.4.0.

Once I get 1.4.0 to build on CentOS 8 I'll look into backporting what is needed to CentOS 7.

**Comment by namebee** [comment]
Any more info on this?

**Comment by hairmare** [comment]
I have some early results with 1.3.x on CentOS 8 but haven't taken the leap to full-on 1.4 updating yet.

At this point I'm assuming that I wont be able to backport to CentOS 7 so this has taken a bit of a backseat while we prepare our CentOS 8 rollout.

**Comment by namebee** [comment]
Ah that really sucks as I'm just using this standalone on Centos 7, I'm not gonna be able to upgrade.

**Comment by hairmare** [comment]
liquidsoap 1.4.3 packages for CentOS are now available 🚀 

As i was assuming, backporting OCaml in a modern version for CentOS 7 proved to be too much work. If you are on CentOS 7 I recommend you consider upgrading to CentOS 8.

As an added bonus 1.4.3 also marks the first time packages for Fedora are properly available. RPMs for Fedora 32, Fedora 33, and Fedora rawhide are in the repsective repos.
