### ISSUE TITLE
rpm for fedora

### ISSUE THREAD

**Issue by jeremiel26** [radiorabe/centos-rpm-liquidsoap#34]
Hi!
I've seen a repository for fedora:
https://download.opensuse.org/repositories/home:radiorabe:liquidsoap/Fedora_33

but no liquidsoap package in it. Do you think possible to add fedora rpm for liquidsoap?
thx a lot for your great work on centos!

**Comment by hairmare** [comment]
It looks like I will be able to add Fedora packages once I upgrade to liquidsoap 1.4. This will also mark the end of updates for CentOS 7 packages.

**Comment by hairmare** [comment]
liquidsoap 1.4.3 packages for Fedora 32, Fedora 33, and Fedora rawhide are now available from the repo 🚀 

Let me know if you run into any issues.

**Comment by jeremiel26** [comment]
Thank your VERY MUCH!!! So fast :)

**Comment by hairmare** [comment]
I pushed a new version that depends on RPMfusion and also enabled pulseaudio. This should make it more practical in day to day usage on a Fedora Desktop.
