### ISSUE TITLE
liquidsoap@.service - ExecStartPre=/bin/mkdir - (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/centos-rpm-liquidsoap#7]
The [`ExecStartPre=/bin/mkdir  /var/log/liquidsoap`](https://github.com/radiorabe/centos-rpm-liquidsoap/blob/master/liquidsoap%40.service#L10) fails if the directory already exists (which it does after the second start-up of this service.

```
systemctl status liquidsoap@dabplus-on-air-processing
● liquidsoap@dabplus-on-air-processing.service - Liquidsoap
   Loaded: loaded (/usr/lib/systemd/system/liquidsoap@.service; enabled; vendor preset: disabled)
   Active: active (running) since Sam 2016-09-10 13:02:28 CEST; 26min ago
     Docs: http://liquidsoap.fm
           man:liquidsoap(1)
  Process: 4370 ExecStartPre=/bin/chown liquidsoap /var/log/liquidsoap (code=exited, status=0/SUCCESS)
  Process: 4366 ExecStartPre=/bin/mkdir /var/log/liquidsoap (code=exited, status=1/FAILURE)
```

A simple way to fix this, would be to add the `--parents` option to the `mkdir` call. However, it is probably more appropriate to create the log directory directly within the [liquidsoap.spec](https://github.com/radiorabe/centos-rpm-liquidsoap/blob/master/liquidsoap.spec) RPM.

**Comment by hairmare** [comment]
The `ExecStartPre` is prefixed with a dash, thus ignoring the the failure. Why is this a problem?

I'd rather not have it in the spec since it is up to the user to actually configure this properly (and maybe use a different location or only log to systemd journals using stdout).

**Comment by paraenggu** [comment]
thanks!
