### ISSUE TITLE
Update liquidsoap repo to latest production version?

### ISSUE THREAD

**Issue by amavarick** [radiorabe/centos-rpm-liquidsoap#9]
Not an issue with this github, but would you consider updating your repo to the latest production version of liquidsoap?  They've made some changes to ssl and other bug fixes that are useful.

Thank you for creating such a great thing here.  I believe you are the only full featured, working and actively maintained repo on the net for CentOS without going to some bloated radio package.

**Comment by hairmare** [comment]
We plan on updating to liquidsoap next as soon as it has been released. If I find enough time I'll also put some time into making the install modular (it's one large static binary right now).

I'll keep this open until liquidsoap is released and the packages are updated.

Thanks for the feedback!

**Comment by hairmare** [comment]
The package just built and the repo was updated. Sadly, there still isn't any SSL support for CentOS because `ocaml-ssl` which is in EPEL7 needs an update. I'd prefer to not have any packages in the repo that update parts of CentOS core or EPEL7.

**Comment by hairmare** [comment]
BTW, I'll ask for a EPEL bump once https://bugzilla.redhat.com/show_bug.cgi?id=1446335 is merged.
